### ISSUE TITLE
Modify the CoFEA so that it exports mesh which can be directly imported into Code_Aster not only to Salome

### ISSUE THREAD

**Issue by spolanski** [spolanski/CoFEA#20]
- [ ] add information about CSYS into unv file
- [ ] add information about units

**Comment by dantelimac** [comment]
Done. If it's satisfactory, the issue can be closed.

**Comment by spolanski** [comment]
I think you read my mind :) this is what I wanted. There was one thing that I had to change and it was the walrus operator. I haven't heard about it before, so I see it's potential. Although, I would like to keep the code somehow compatible with Python 2.7 version (at least for now). I will explain why on discord :)
