### ISSUE TITLE
Issue on page /reference/blog/2020-12-10.html

### ISSUE THREAD

**Issue by spacether** [spolanski/CoFEA#22]
Can you add gmsh to your site?

**Comment by spolanski** [comment]
What you exactly mean by adding GMSH to cofea site? Will we said a word about it? Definitely yes. Will the mesh converter support it? There are plans as well to do it

**Comment by spacether** [comment]
I just thought that mentioning it could be helpful, not necessarily supporting it yet.

**Comment by spolanski** [comment]
GMSH will be added at some point. At the moment I am closing the issue
